### PR TITLE
Add option 'initialIndex'

### PR DESCRIPTION
**Pull request by danielj41**
This allows the user to specify an initial slide that should display when lory is first initialized.

As far as I'm aware, there is currently no other way to do this. Please let me know if I missed anything! Thanks :)

Closes https://github.com/meandmax/lory/issues/628

### CODE REVIEW

**Comment by nstanard** [comment]
@danielj41 I'll have to go through and test this. I was hoping to talk to you about why you need/want this feature though. Seems to me ordering the slides in the order you want them to display is pretty standard. Is there a scenario you are having to program for that is causing you to want this feature?

I am also thinking you could turn off the rewind option when you init the slider and add your own resize event that calls slideTo for the index you want to be the first to display. I don't want to block such a simple addition to the project, however, I will first want to talk to you about your use case that requires this.

**Comment by danielj41** [comment]
Sure, that's a reasonable question.

We're using `lory` to display photos of a product. See this screenshot:

white

This product comes in multiple colors, which can be selected with the dropdown menu. When this dropdown state changes, we store the new state in the url with `replaceState`.

If the user reloads the page, we want to show the first image that corresponds to the selected color. See this screenshot:

black

You can [try this page yourself](https://www.ifixit.com/Store/Parts/Galaxy-S7-LCD-Screen-and-Digitizer/IF329-000-2). View it on a mobile device (or a window narrower than 600px).

We did try using `slideTo`, as suggested. However, I couldn't find a way to temporarily disable the sliding animation. It looked odd to animate away from the first image as soon as the page loaded.

**Comment by nstanard** [comment]
That makes a lot of sense! I'll try to look closer at this sometime this week. Again, thank you for opening a PR and contributing.

**Comment by qkevinto** [comment]
@nstanard, have you had a chance to look into this PR? This is a feature I would find useful as well. 😀

**Comment by psi-4ward** [comment]
+1

**Comment by meandmax** [comment]
@danielj41 I will checkout this branch, build dist files and then merge it.

Please keep http://commitizen.github.io/cz-cli/ in mind, otherwise the auto build/deployment with semantic-release wont work.

Thanks for contributing!

**Comment by meandmax** [comment]
in favor of https://github.com/meandmax/lory/pull/717

@danielj41 thanks for contributing!

**Pull request closed without merging**
