### PR TITLE
Fixed issue when using with SSR apps due to window not being defined

### PR DESCRIPTION
**Pull request by MrSlide**
When using Lory in applications that use server side rendering (SSR), like Vue.js or React applications, rendering the applications fails due to Lory trying to use the `window` object.

This fix checks that `window` is defined, and if not, uses `null` as the default value for `window`.

### CODE REVIEW

**Comment by Saturate** [comment]
Hey @MrSlide thanks for the PR! Unfortunately there are some conflicts, due to other updates that must be fixed. It seems like all that's needed is a new build , but none the less it's needed.

Thanks!

**Comment by MrSlide** [comment]
Hi @Saturate 
I just resolved all the conflicts

**Comment by Saturate** [comment]
Hi @MrSlide it still conflicts for me :-(

**Comment by MrSlide** [comment]
@Saturate I fixed the merge conflicts again, only the dist files are conflicting, this will happen every time something is merged with the master branch but can easily be fixed by just creating a new build.

**Comment by meandmax** [comment]
I merge this now, but again need to add an empty trigger commit to the master to trigger a build. Please keep in mind that if you do your commits use either https://github.com/commitizen/cz-cli or just do it manually. Check out this: https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commits

cheers

**Pull request merged**
