### PR TITLE
Bugfix/support passive

### PR DESCRIPTION
**Pull request by jacobjuul**
Fixes issue #709

### CODE REVIEW

**Comment by heinrichson** [comment]
Lets get this for improved scrolling performance

**Comment by praneybehl** [comment]
Can this pull request be merged? The browser console keeps through Violation warnings and they also reflect on google anaylytics 

image

**Comment by s3rgiosan** [comment]
@jacobjuul can you update the dist files in your branch? I want to use your fix via npm.

**Comment by jacobjuul** [comment]
@s3rgiosan updated, please let me know how it works out for you.

**Comment by s3rgiosan** [comment]
Worked like a charm. Thanks 👍

**Comment by Saturate** [comment]
@meandmax this looks good to merge, it could seem that you are busy. Do you need some help maintaining this repo?

**Comment by meandmax** [comment]
@Saturate added you to contributors, thanks for offering help!

**Comment by meandmax** [comment]
For future pull-requests please keep in mind that the deployment won`t work if the commit messages are not in the right format.

Check this out: http://commitizen.github.io/cz-cli/

**Comment by jacobjuul** [comment]
@meandmax I'd be happy to help as well

**Pull request merged**
