### PR TITLE
Add centerMode option (and add current() to public API)

### LINKED ISSUE #11: feature request: centerMode option (ref: slick)
Hello.

I currently working replace carousel library from [slick](http://kenwheeler.github.io/slick/) to lory.

This work want to centerMode option of slick, but lory is not implement centerMode option.

Are you planning to do it in the future?

Thanks.

### PR DESCRIPTION
**Pull request by kubosho**
Hi, @meandmax.

I fixed #11 feature request: centerMode option (ref: slick). Please let me know if you have advice or questions.

Thanks.

### CODE REVIEW

**Comment by meandmax** [comment]
Hey @kubosho,

Im nearly finished with reviewing your request! Thank you very much for your engagement. I will checkout your pull request in the evening, doing some last tests! Looking forward to merge it!

cheers and thanks a lot!
Max

**Comment by kubosho** [comment]
Hi, @meandmax.

Thanks a lot for your code review, and I resolved code.

**Comment by meandmax** [comment]
Hey @kubosho,

I merged your pull-request and found afterwards a bug. The center slide isn`t centered correctly. It seems to be that I can`t reopen this request, so could you please make a new request.

Thank you
Max

**Comment by meandmax** [comment]
Im not sure why we need to add classes like "js_current" or "js_clone". Could you explain me for which purpose did you add them and also the function setCurrentSelector.

If you make a new pull-request I will look into it.

cheers Max

**Pull request merged**
