### PR TITLE
Destroy cloned slides if infinite is set

### PR DESCRIPTION
**Pull request by ght**

### CODE REVIEW

**Comment by ght** [comment]
Builds fine locally, fails on Travis-CI with the notice **"Make sure the SAUCE_USERNAME and SAUCE_ACCESS_KEY environment variables are set."**

If I did something wrong, please let me know how to fix it.

**Comment by meandmax** [comment]
Please rebase with current master ... tests should run through now! Thx for contribution!

Max

**Comment by meandmax** [comment]
👍  Could you just change your commit msg to `fix:Destroy cloned slides if infinite is set` otherwise semantic-release does not know what to do ...

Thanks for contributing!
Max

**Comment by ght** [comment]
Renamed and rebased onto master.

**Pull request merged**
