### PR TITLE
Fix for android touchmove bug

### PR DESCRIPTION
**Pull request by arcxyz**
There is a bug with touch events on the default browser of some android devices:
https://code.google.com/p/android/issues/detail?id=5491

This fix adds a preventDefault() to the touchmove event when the user is not trying to scroll vertically.

The bug is not possible to reproduce on android emulator (don't know why :confused: ). Only with real devices

### CODE REVIEW

**Comment by meandmax** [comment]
Hey @arcxyz,

thank you very much for the change request. I think I had a similar issue in the chrome emulator a few days ago. Can you explain me the bug a bit more specific just to understand if it`s the same problem (stuttering slider animation because too few move events ... )?

Are you sure it works if you put event.preventDefault() in the onTouchmove function? In the discussion above they talking about adding preventDefault in the onTouchstart function and as I remember I had it in the first time also in the onTouchstart function.

I will check this for HTC Desire and Samsung Galaxy s2. Did you check if the preventDefault solves the issue on a real device? Please tell me with which device you tested the bugfix.

I'll be in touch again soon
cheers Max

**Comment by arcxyz** [comment]
Finally, I was able to reproduce on the android emulator the same behaviour that I get with a Nexus S, changing the translate3d with a translateX 
lory
(you cannot complete the scroll)

If you put the preventDefault in the onTouchstart function it will affect to click events. Check this link:
https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Touch_events#Handling_clicks

With this bugfix I get it working for Nexus S. But I've also tested with a Galaxy S, Galaxy Mini and HTC Wildfire and does not work at all, but this is probably related by the lack of support of 3d transforms on android 2.2 and 2.3.

Do not merge, tomorrow I will try to get it working on these other devices.

**Comment by arcxyz** [comment]
It is working great now for Galaxy Mini, Galaxy S and HTC Wildfire. Could you check it with your HTC Desire or Galaxy S2?
http://arcxyz.github.io/fix-android-touchmove/

**Comment by meandmax** [comment]
Hey @arcxyz,

thank you for your engagement! Honestly I didn´t change anything in the touchevent logic, but I`m very happy that it works now for you. As I can see, browser transitions are not supported in Android 2.x ... therefore it works on some devices but I can´t guarantee it for now. I will double check on which devices it works as expected and then I will put them in the documentation.

Thanks again
cheers Max

**Pull request closed without merging**
