### PR TITLE
Simple element - dot navigation

### PR DESCRIPTION
**Pull request by nstanard**
Dot navigation example added to the demo site. This shows people how to use the public API and create a simple dot navigation to get them started.

### CODE REVIEW

**Comment by meandmax** [comment]
fixes #323

**Comment by nstanard** [comment]
I would be happy to add that as well.

**Comment by nstanard** [comment]
#323 Fixed with an example to the demo site. 
The requested changes were made. @meandmax

**Comment by nstanard** [comment]
Added a resize event as well to reset the dots instead of the proposal I made. @meandmax

**Pull request merged**
