### PR TITLE
detect translate3d and fall back to translate (ie9 support)

### PR DESCRIPTION
**Pull request by levito**
Moin Max,

IE9 doesn't support translate3d, so I added a feature-detect for it.

This commit fixes IE9 support (users will still have to include classlist polyfill).

Cheers
Veit

### CODE REVIEW

**Comment by meandmax** [comment]
Hey @levito,

the solution looks good to me, just remove the version because this works in lory over semantic-release which means you have to write proper commit messages as described in the following resources:

https://github.com/semantic-release/semantic-release
https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md

I also updated to babel 6 ... finally, so would be nice if you rebase your master first before making a pull request or I will rebase it afterwards.

Thanks anyways
Max

**Comment by levito** [comment]
Hi @meandmax,

I just rebased on upstream and removed the version number from the package.json. I needed to add it so I can npm-install my fork. My bad it landed in the PR.

Cheers
Veit

**Comment by meandmax** [comment]
Changed your commit-messages in order that semantic-release works as expected. And pushed your changes in a seperate branch.

https://github.com/meandmax/lory/pull/92

cheers Max

**Comment by levito** [comment]
Thanks a lot, Max!

**Pull request closed without merging**
