### PR TITLE
Fixed event 'before.lory.slide' reporting wrong 'nextSlide'

### LINKED ISSUE #520: Event 'before.lory.slide' reports wrong 'nextSlide'
The slides reported by the `before.lory.slide` event are wrong when the method `slideTo( k )` is used.

This because the value `nextSlide `is defined by `direction ` and by incrementing the current `index`;
 ```javascript
var nextSlide = direction ? index + 1 : index - 1;

dispatchSliderEvent('before', 'slide', {
    index: index,
    nextSlide: nextSlide
});
```

The following example:
```javascript
var simple =  lory(target, {
    infinite: 1,
    slidesToScroll: 1
});

// Listeners
body.addEventListener('before.lory.slide', function(e){
  console.log("before(" + e.detail.index + " => " + e.detail.nextSlide + ")");
});
body.addEventListener('after.lory.slide', function(e){
  console.log("after(" + e.detail.currentSlide + ")");
});

simple.slideTo(3);
simple.slideTo(1);
```

will return the follow output
```
before(1 => 0)
after(4)
before(4 => 3)
after(2)
```

instead of
```
before(1 => 4)
after(4)
before(4 => 2)
after(2)
```

### PR DESCRIPTION
**Pull request by UTurista**
Used the already existing and correctly calculated value that defines the next index.
In the carrousel case the value is also checked if is going past the actual number of slides and properly wrapped.

Fixes #520

### CODE REVIEW

**Comment by boneyfantaseas** [comment]
I'd love to see this pull request resolved as I encounter this issue currently on building an index/total display.

**Comment by andrejpavlovic** [comment]
Ideally the dist files should not be part of the pull request...

**Comment by meandmax** [comment]
@UTurista Could someone give me an update on this? If this is still an issue please rebase to the current master and make sure it works. Then I will merge this asap! And Im very sorry for the late response, Time to do some housework here. :)

@andrejpavlovic we need the dist files in the npm package.

**Comment by Insasse** [comment]
Would you reroll the patch against latest version please?

**Comment by Insasse** [comment]
I have a similiar problem with my slider, the slider seems to randomly skipping 2-3 slides, the slidesToScroll is set to 1, though.

**Comment by UTurista** [comment]
I checked the current version (2.5.1) and the error was still present.

**Pull request closed without merging**
