### PR TITLE
	Add a possibility to work as a vertical slider

### PR DESCRIPTION
**Pull request by lacedon**
#684 

Added option vertical(default false) to switch lory to work as a vertical slider.

### CODE REVIEW

**Comment by meandmax** [comment]
Nice work! I will check it out and test if everything works as expected. Please align your commits to https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit, otherwise semantic release doesnt know what to do.

**Comment by meandmax** [comment]
@lacedon Did you try this out with the examples in the index file because it seems to me that this does not work at all?

**Comment by lacedon** [comment]
Actualy, no, I didn't, but I'm using it on my project as vertical and as horizontal slider.
I'll try to check it and fix my commits tomorrow.

**Comment by lacedon** [comment]
Pull request was redone here: #693.

**Pull request closed without merging**
