### PR TITLE
Re: Add centerMode option

### LINKED ISSUE #11: feature request: centerMode option (ref: slick)
Hello.

I currently working replace carousel library from [slick](http://kenwheeler.github.io/slick/) to lory.

This work want to centerMode option of slick, but lory is not implement centerMode option.

Are you planning to do it in the future?

Thanks.

### PR DESCRIPTION
**Pull request by kubosho**
Hi, @meandmax.

I fixed #11 #16.

Delete setCurrentSelector function and "js_current" & "js_clone" selectors (because it was not necessary).

Please let me know if you have advice or questions.

Thanks.

### CODE REVIEW

**Comment by kubosho** [comment]
@meandmax 
Didn't fix following bugs, sorry. I fix bug "center slide isn't centered correctly" as soon.
https://github.com/meandmax/lory/pull/16#issuecomment-94311486

**Comment by meandmax** [comment]
For positioning maybe something like this:

```js
(slides[index].offsetLeft - (frameWidth / 2) + (slides[index].clientWidth / 2)) * -1
```

instead of:

```js
slides[nextIndex].offsetLeft * -1
```

cheers Max

**Comment by kubosho** [comment]
@meandmax 
Thanks for advice, and change code at https://github.com/meandmax/lory/blob/master/src/lory.js#L315.

before:
```js
var nextOffset = limitOffset(slides[nextIndex].offsetLeft * -1);
```

after:
```js
var nextOffset = limitOffset(slides[nextIndex].offsetLeft * -1);

if (options.centerMode) {
    nextOffset = limitOffset((slides[index].offsetLeft - (frameWidth / 2) + (slides[index].clientWidth / 2)) * -1);
}
```

result:
centermode

It looks buggy. I continue to fix bug.

**Comment by kubosho** [comment]
@meandmax 
I fixed "center slide isn't centered correctly" bug c9b9f4dc. I guess it worked.

centermode-demo

**Comment by kubosho** [comment]
@meandmax 
I removed current function, because I felt it unnecessary and not casually add function to public API.

**Comment by meandmax** [comment]
Thanks a lot @kubosho, it`s getting better! Still the slide is not centered correctly and I was also wondering why it is necessary to use centerMode in combination with infinite.

I really think I have to rewrite a couple of things to get this feature up and running without infinite while keeping the current size of the slider.

cheers Max

**Comment by kubosho** [comment]
@meandmax 
I fixed "slide is not centered correctly" to 2e64c964b17a:
screen recording 2015-04-22 at 01 52 am
jsfiddle: https://jsfiddle.net/Lm8L8r51/11/embedded/result/

> I really think I have to rewrite a couple of things to get this feature up and running without infinite while keeping the current size of the slider.

Which of the following is closest in meaning?

1. delete code to https://github.com/kubosho/lory/blob/feat/center-mode/src/lory.js#L198-L200
1.  http://codepen.io/kubosho_/pen/yNLNEe the look like be rewritten

**Pull request closed without merging**
