### PR TITLE
README matches demo site for NPM commands now

### PR DESCRIPTION
**Pull request by nstanard**
#434 Fixed @meandmax

### CODE REVIEW

**Comment by meandmax** [comment]
`npm run dev` starts the server with `nodemon` so if u change config files e.g. `webpack.config.js` the server restarts.

https://github.com/meandmax/lory/blob/master/package.json#L91

There is also a `npm run karma-local` which runs the tests with the local browser launchers.

I think we should make the changes the other way around. The commands in the readme are the newer ones .

So I suggest adjusting `npm start` to `npm run dev` and `npm run karma` to `npm run karma-local`.

Thanks anyways!

**Comment by nstanard** [comment]
Ah I see. I'll switch that around.

**Comment by nstanard** [comment]
Alright I took a minute and switched that around. @meandmax

**Comment by meandmax** [comment]
👍  Thx

**Comment by meandmax** [comment]
Fixes  #448

**Pull request merged**
